# Generated by Django 4.2.7 on 2023-11-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=30, verbose_name="Имя модели")),
                ("function", models.CharField(max_length=30, verbose_name="Функция")),
                ("data", models.CharField(max_length=10000, verbose_name="Данные")),
            ],
        ),
    ]
