# Generated by Django 4.2.7 on 2023-11-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("load_and_show_json", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="model",
            new_name="module",
        ),
        migrations.RemoveField(
            model_name="module",
            name="data",
        ),
        migrations.CreateModel(
            name="FullModuleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=30, verbose_name="Описание"),
                ),
                ("version", models.CharField(max_length=100, verbose_name="Версия")),
                ("value", models.CharField(max_length=1000, verbose_name="Массив")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="full",
                        to="load_and_show_json.module",
                        verbose_name="Модуль",
                    ),
                ),
            ],
        ),
    ]
